libraries:
  zlib:
    all:
      version: "1.3.1"
      url: "https://zlib.net/zlib-1.3.1.tar.gz"
      sha256: "9a93b2b7dfdac77ceba5a558a580e74667dd6fede4585b91eefb60f03b72df23"
  libexpat:
    all:
      version: "2.7.3"
      url: "https://github.com/libexpat/libexpat/releases/download/R_2_7_3/expat-2.7.3.tar.gz"
      sha256: "821ac9710d2c073eaf13e1b1895a9c9aa66c1157a99635c639fbff65cdbdd732"
  # openssl:
  #   version 3.x.y requires pod2man, that is not easily available on Windows x64
  #   Windows ARM64 requires OpenSSL 3.3.2 (1.1.1w is x86_64 only)
  openssl:
    windows-x64:
      version: "1.1.1w"
      url: "https://github.com/openssl/openssl/releases/download/OpenSSL_1_1_1w/openssl-1.1.1w.tar.gz"
      sha256: "cf3098950cb4d853ad95c0841f1f9c6d3dc102dccfcacd521d93925208b76ac8"
    windows-arm64:
      version: "3.3.2"
      url: "https://github.com/openssl/openssl/releases/download/openssl-3.3.2/openssl-3.3.2.tar.gz"
      sha256: "2e8a40b01979afe8be0bbfb3de5dc1c6709fedb46d6c89c10da114ab5fc3d281"
    all:
      version: "3.3.2"
      url: "https://github.com/openssl/openssl/releases/download/openssl-3.3.2/openssl-3.3.2.tar.gz"
      sha256: "2e8a40b01979afe8be0bbfb3de5dc1c6709fedb46d6c89c10da114ab5fc3d281"
  # xz:
  #   versions > 5.2.4 get crazy on MinGW
  #   versions <= 5.2.5 do not support arm64-apple-darwin target
  #   version 5.2.7 could not be linked statically to libarchive
  xz:
    windows:
      version: "5.2.4"
      url: "https://tukaani.org/xz/xz-5.2.4.tar.gz"
      sha256: "b512f3b726d3b37b6dc4c8570e137b9311e7552e8ccbab4d39d47ce5f4177145"
    all:
      version: "5.2.6"
      url: "https://tukaani.org/xz/xz-5.2.6.tar.gz"
      sha256: "a2105abee17bcd2ebd15ced31b4f5eda6e17efd6b10f921a01cda4a44c91b3a0"
  libarchive:
    all:
      version: "3.8.4"
      url: "https://www.libarchive.org/downloads/libarchive-3.8.4.tar.gz"
      sha256: "b2c75b132a0ec43274d2867221befcb425034cd038e465afbfad09911abb1abb"
